#!/usr/bin/env bash

docker_cli_plugin_metadata() {

        local version=0.1
	local vendor="tomwillfixit"
	local url="https://tomwillfixit.com"
	local description="Display CHANGELOG for installed Docker version"
	cat <<-EOF
	{"SchemaVersion":"0.1.0","Vendor":"${vendor}","Version":"${version}","ShortDescription":"${description}","URL":"${url}"}
EOF
}

case "$1" in
	docker-cli-plugin-metadata)
		docker_cli_plugin_metadata
		;;
	*)
		exec "curl -s https://raw.githubusercontent.com/docker/docker-ce/v$(docker version — format “{{.Client.Version}}”)/CHANGELOG.md"
		;;
esac

